### ISSUE TITLE
PropertyNotFoundException with JFXTextField

### ISSUE THREAD

**Issue by syednoman84** [afsalashyana/Library-Assistant#6]
Hi,

Thank you so much for such a  good project. I am following your YouTube series for this Library Assistant to learn javaFX. I am new to this whole world so please excuse me for any silly questions :)

The problem I am facing is that the moment I set Margin for my JFXTextField in SceneBuilder, save and close the SceneBuilder. My fxml document is updated to show me these properties but when I try to open that fxml document again via Eclipse by simply using option in Eclipse on my fxml file saying "Open with Scene Builder", the Scene Builder throws following error:

java.io.IOException: javafx.fxml.LoadException: 
/C:/Users/snoman/workspace/JavaFX/Library%20Assistant/src/library/assistant/ui/addbook/FXMLDocument.fxml:15

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:92)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:80)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:95)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2370)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:655)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:386)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:579)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:447)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleLaunch(SceneBuilderApp.java:427)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStartGeneric(AppPlatform.java:139)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStart(AppPlatform.java:106)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.start(SceneBuilderApp.java:371)
	at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
	at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
	at com.sun.glass.ui.win.WinApplication$4$1.run(WinApplication.java:112)
	at java.lang.Thread.run(Thread.java:744)
Caused by: javafx.fxml.LoadException: 
/C:/Users/snoman/workspace/JavaFX/Library%20Assistant/src/library/assistant/ui/addbook/FXMLDocument.fxml:15

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2617)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:89)
	... 22 more
Caused by: com.sun.javafx.fxml.PropertyNotFoundException: Static property "margin" does not exist or is read-only.
	at com.sun.javafx.fxml.BeanAdapter.put(BeanAdapter.java:595)
	at javafx.fxml.FXMLLoader$PropertyElement.set(FXMLLoader.java:1414)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:784)
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2839)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532)
	... 24 more

Here is my fxml file code and I am using the latest jfoenix jar version 8.0.8 which I downloaded from https://github.com/jfoenixadmin/JFoenix

[myFXMLFileCode.txt](https://github.com/afsalashyana/Library-Assistant/files/2799220/myFXMLFileCode.txt)

[ErrorStack_JFXTextField.txt](https://github.com/afsalashyana/Library-Assistant/files/2799221/ErrorStack_JFXTextField.txt)

I will be grateful to you if you help me in resolving this issue. Thanks a lot.

**Comment by syednoman84** [comment]
One more thing I noticed that although this error comes up when I am trying to open the fxml from Eclipse but when I run the project, the JVM does not throw any error and loads my application perfectly.

**Comment by afsalashyana** [comment]
Hi,
I tried to reproduce this issue. I am using NetBeans (which shouldn't matter since exception is thrown by Scene Builder). 
I checked with 'myFXMLFileCode.txt' FXML content and it is working fine.

Make sure the following things in your environment.

1. Use latest Scene Builder from [here](https://gluonhq.com/products/scene-builder/). **Make sure you download version matching your Java version**. If you are using Java 8, make sure you get Scene Builder for Java 8.
>The latest version of Scene Builder for Java 8 is 8.5.0, it was released on Jun 5, 2018.
2. Make sure you are using correct JFoenix. Download JFoenix matching your JDK.

**Comment by syednoman84** [comment]
Thank you so much buddy. The problem got resolved after I used the latest version of Scene Builder from your provided link. The JFoenix I already had the correct version as you mentioned. Now I am able to load my fxml from Eclipse.

Really appreciate your time and support. You and your library assistant project have been a great help for me to learn Java end to end.

**Comment by afsalashyana** [comment]
You are welcome.
👍
